#!/bin/bash

# Railway Environment Setup Script
# Run this script to get the exact commands to set environment variables

echo "🔧 Railway Environment Variable Setup"
echo "======================================"
echo ""

echo "📋 FRONTEND SERVICE ENVIRONMENT VARIABLES"
echo "----------------------------------------"
echo "Set these in Railway Dashboard for your FRONTEND service:"
echo ""
echo "REACT_APP_API_URL=https://[YOUR-BACKEND-SERVICE-NAME].railway.app"
echo "NODE_ENV=production"
echo "GENERATE_SOURCEMAP=false"
echo ""
echo "⚠️  IMPORTANT: Replace [YOUR-BACKEND-SERVICE-NAME] with your actual backend service name!"
echo ""

echo "📋 BACKEND SERVICE ENVIRONMENT VARIABLES"
echo "---------------------------------------"
echo "Set these in Railway Dashboard for your BACKEND service:"
echo ""
echo "FLASK_ENV=production"
echo "FLASK_APP=start.py"
echo "SECRET_KEY=your-secret-key-here-make-it-random"
echo ""
echo "Optional (if using these services):"
echo "DATABASE_URL=your-database-url"
echo "SUPABASE_URL=your-supabase-url"
echo "SUPABASE_ANON_KEY=your-supabase-anon-key"
echo "OLLAMA_BASE_URL=your-ollama-url"
echo ""

echo "🚀 DEPLOYMENT STEPS"
echo "==================="
echo "1. Set the environment variables above in Railway Dashboard"
echo "2. Push your code changes (we added debugging)"
echo "3. Railway will automatically redeploy"
echo "4. Check debug pages:"
echo "   - Frontend: https://[your-frontend-url]/debug"
echo "   - Backend: https://[your-backend-url]/debug"
echo ""

echo "🔍 DEBUGGING URLS (after deployment)"
echo "===================================="
echo "Frontend Debug: https://[your-frontend-service].railway.app/debug"
echo "Frontend Health: https://[your-frontend-service].railway.app/health"
echo "Backend Debug: https://[your-backend-service].railway.app/debug"
echo "Backend Health: https://[your-backend-service].railway.app/api/health"
echo ""

echo "💡 HOW TO FIND YOUR SERVICE NAMES"
echo "================================="
echo "1. Go to Railway Dashboard"
echo "2. Select your project"
echo "3. You'll see service cards (e.g., 'web', 'backend', 'frontend')"
echo "4. The URL format is: https://[service-name]-[random-id].railway.app"
echo ""

echo "✅ QUICK TEST"
echo "============"
echo "After setting variables and deploying:"
echo "1. Visit your frontend URL"
echo "2. If you see a blank page, go to [frontend-url]/debug"
echo "3. Check the debug information for missing variables"
echo "4. Check Railway logs for detailed error messages"
